--liquibase formatted sql

--changeset raza:cv_germplasm_species_seed_data context:seed_general splitStatements:false

/* 
CV terms seed data for  germplasm_species  
*/

 Select * from createCVinGroup('germplasm_species',1,'Zea mays subsp. mays','Zea mays subsp. mays',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Zea mays subsp. mexicana','Zea mays subsp. mexicana',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Zea mays subsp. parviglumis','Zea mays subsp. parviglumis',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Zea mays subsp. huehuetenangensis','Zea mays subsp. huehuetenangensis',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Zea diploperennis','Zea diploperennis',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Tripsacum andersonii','Tripsacum andersonii',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Tripsacum australe var. australe','Tripsacum australe var. australe',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Tripsacum bravum','Tripsacum bravum',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Tripsacum cundinamarcae','Tripsacum cundinamarcae',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Tripsacum dactyloides','Tripsacum dactyloides',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Tripsacum dactyloides var. hispidum','Tripsacum dactyloides var. hispidum',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Tripsacum dactyloides var. meridonale','Tripsacum dactyloides var. meridonale',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Tripsacum dactyloides var. mexicanum','Tripsacum dactyloides var. mexicanum',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Tripsacum intermedium','Tripsacum intermedium',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Tripsacum jalapense','Tripsacum jalapense',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Tripsacum lanceolatum','Tripsacum lanceolatum',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Tripsacum latifolium','Tripsacum latifolium',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Tripsacum laxum','Tripsacum laxum',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Tripsacum maizar','Tripsacum maizar',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Tripsacum manisuroides','Tripsacum manisuroides',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Tripsacum peruvianum','Tripsacum peruvianum',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Tripsacum pilosum','Tripsacum pilosum',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Tripsacum zopilotense','Tripsacum zopilotense',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Undetermined spp.','Undetermined spp.',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Unknown','Unknown',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Triticum aestivum subsp. aestivum','Triticum aestivum subsp. aestivum',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Triticum turgidum subsp. durum  ','Triticum turgidum subsp. durum  ',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Triticum turgidum subsp. polonicum','Triticum turgidum subsp. polonicum',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Triticum turgidum subsp. turgidum','Triticum turgidum subsp. turgidum',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Triticum turgidum subsp. carthlicum','Triticum turgidum subsp. carthlicum',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Triticum turgidum subsp. turanicum','Triticum turgidum subsp. turanicum',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Triticum aestivum subsp. compactum','Triticum aestivum subsp. compactum',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Triticum turgidum subsp. dicoccon','Triticum turgidum subsp. dicoccon',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Triticum aestivum subsp. spelta','Triticum aestivum subsp. spelta',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Secale cereale','Secale cereale',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Aegilops squarrosa','Aegilops squarrosa',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Triticum monococcum subsp. monococcum','Triticum monococcum subsp. monococcum',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Triticum turgidum subsp. dicoccoides','Triticum turgidum subsp. dicoccoides',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Triticum aestivum subsp. sphaerococcum','Triticum aestivum subsp. sphaerococcum',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Triticum urartu','Triticum urartu',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Triticum boeoticum','Triticum boeoticum',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Triticum monococcum','Triticum monococcum',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Aegilops speltoides','Aegilops speltoides',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Hordeum vulgare','Hordeum vulgare',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Aegilops biuncialis','Aegilops biuncialis',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Aegilops kotschyi','Aegilops kotschyi',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Aegilops longissima','Aegilops longissima',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Aegilops umbellulata','Aegilops umbellulata',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Aegilops cylindrica','Aegilops cylindrica',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Aegilops geniculata','Aegilops geniculata',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Aegilops columnaris','Aegilops columnaris',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Aegilops comosa','Aegilops comosa',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Aegilops peregrina','Aegilops peregrina',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Triticum aestivum subsp. macha','Triticum aestivum subsp. macha',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Triticum timopheevii subsp. timopheevii','Triticum timopheevii subsp. timopheevii',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Triticum monococcum subsp. aegilopoides','Triticum monococcum subsp. aegilopoides',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Aegilops triuncialis','Aegilops triuncialis',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Aegilops tauschii subsp. strangulata','Aegilops tauschii subsp. strangulata',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Aegilops tauschii var. meyerii','Aegilops tauschii var. meyerii',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'hordeum vulgare subsp. vulgare','hordeum vulgare subsp. vulgare',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Triticum zhukovskyi','Triticum zhukovskyi',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Triticum turgidum subsp. paleocolchicum','Triticum turgidum subsp. paleocolchicum',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Triticum timopheevii subsp. armeniacum','Triticum timopheevii subsp. armeniacum',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Triticum spp.','Triticum spp.',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Aegilops crassa','Aegilops crassa',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Triticum hybr.','Triticum hybr.',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Triticum vavilovii var. vavilovii','Triticum vavilovii var. vavilovii',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'x Tritordeum','x Tritordeum',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Aegilops tauschii x Triticum turgidum','Aegilops tauschii x Triticum turgidum',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'x Aegilotriticum','x Aegilotriticum',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'x Triticosecale','x Triticosecale',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'x Triticoaegilops','x Triticoaegilops',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Undetermined','Undetermined',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Aegilops tauschii','Aegilops tauschii',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Agropyron','Agropyron',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Oryza sativa','Oryza sativa',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Oryza australiensis','Oryza australiensis',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Oryza barthii','Oryza barthii',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Oryza glaberrima','Oryza glaberrima',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Oryza longistaminata','Oryza longistaminata',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Oryza punctata','Oryza punctata',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Oryza rufipogon','Oryza rufipogon',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Oryza nivara','Oryza nivara',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Oryza meridionalis','Oryza meridionalis',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Oryza glumipatula','Oryza glumipatula',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Oryza minuta','Oryza minuta',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Oryza officinalis','Oryza officinalis',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Oryza alta','Oryza alta',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Oryza coarctata','Oryza coarctata',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Oryza brachyantha','Oryza brachyantha',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Oryza ridleyi','Oryza ridleyi',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Oryza granulata','Oryza granulata',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Cicer arietinum','Cicer arietinum',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Cicer reticulatum','Cicer reticulatum',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Cicer echinospermum','Cicer echinospermum',0,NUll,NULL,1);
 Select * from createCVinGroup('germplasm_species',1,'Sorghum bicolor','Sorghum bicolor',0,NUll,NULL,1);
