package org.gobiiproject.gobiimodel.dto.types;

/**
 * Created by Phil on 5/13/2016.
 */
public enum ServiceRequestId {
    URL_AUTH,
    URL_PING_EXTRACT,
    URL_PING,
    URL_PROJECT,
    URL_NAME_ID_LIST,
    URL_FILE_LOAD_INSTRUCTIONS,
    URL_FILE_EXTRACTOR_INSTRUCTIONS,
    URL_DISPLAY,
    URL_CV,
    URL_CONTACT,
    URL_REFERENCE,
    URL_EXPERIMENT,
    URL_DATASET,
    URL_ANALYSIS,
    URL_MARKERGROUP,
    URL_MANIFEST,
    URL_ORGANIZATION,
    URL_PLATFORM,
    URL_MAPSET,
    URL_CONFIGSETTINGS
}
