package org.gobiiproject.gobiidao.entity.pojos;
// Generated Mar 31, 2016 1:44:38 PM by Hibernate Tools 3.2.2.GA


import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Analysis generated by hbm2java
 */
@Entity
@Table(name="analysis"
    ,schema="public"
)
public class Analysis  implements java.io.Serializable {


     private int analysisId;
     private String analysisName;
     private String analysisDescription;
     private int anlaysisTypeId;
     private String program;
     private String programversion;
     private String algorithm;
     private String sourcename;
     private String sourceversion;
     private String sourceuri;
     private Integer referenceId;
     private Serializable parameters;
     private Date timeexecuted;
     private int status;

    public Analysis() {
    }

	
    public Analysis(int analysisId, int anlaysisTypeId, int status) {
        this.analysisId = analysisId;
        this.anlaysisTypeId = anlaysisTypeId;
        this.status = status;
    }
    public Analysis(int analysisId, String analysisName, String analysisDescription, int anlaysisTypeId, String program, String programversion, String algorithm, String sourcename, String sourceversion, String sourceuri, Integer referenceId, Serializable parameters, Date timeexecuted, int status) {
       this.analysisId = analysisId;
       this.analysisName = analysisName;
       this.analysisDescription = analysisDescription;
       this.anlaysisTypeId = anlaysisTypeId;
       this.program = program;
       this.programversion = programversion;
       this.algorithm = algorithm;
       this.sourcename = sourcename;
       this.sourceversion = sourceversion;
       this.sourceuri = sourceuri;
       this.referenceId = referenceId;
       this.parameters = parameters;
       this.timeexecuted = timeexecuted;
       this.status = status;
    }
   
     @Id 
    
    @Column(name="analysis_id", unique=true, nullable=false)
    public int getAnalysisId() {
        return this.analysisId;
    }
    
    public void setAnalysisId(int analysisId) {
        this.analysisId = analysisId;
    }
    
    @Column(name="analysis_name")
    public String getAnalysisName() {
        return this.analysisName;
    }
    
    public void setAnalysisName(String analysisName) {
        this.analysisName = analysisName;
    }
    
    @Column(name="analysis_description")
    public String getAnalysisDescription() {
        return this.analysisDescription;
    }
    
    public void setAnalysisDescription(String analysisDescription) {
        this.analysisDescription = analysisDescription;
    }
    
    @Column(name="anlaysis_type_id", nullable=false)
    public int getAnlaysisTypeId() {
        return this.anlaysisTypeId;
    }
    
    public void setAnlaysisTypeId(int anlaysisTypeId) {
        this.anlaysisTypeId = anlaysisTypeId;
    }
    
    @Column(name="program")
    public String getProgram() {
        return this.program;
    }
    
    public void setProgram(String program) {
        this.program = program;
    }
    
    @Column(name="programversion")
    public String getProgramversion() {
        return this.programversion;
    }
    
    public void setProgramversion(String programversion) {
        this.programversion = programversion;
    }
    
    @Column(name="algorithm")
    public String getAlgorithm() {
        return this.algorithm;
    }
    
    public void setAlgorithm(String algorithm) {
        this.algorithm = algorithm;
    }
    
    @Column(name="sourcename")
    public String getSourcename() {
        return this.sourcename;
    }
    
    public void setSourcename(String sourcename) {
        this.sourcename = sourcename;
    }
    
    @Column(name="sourceversion")
    public String getSourceversion() {
        return this.sourceversion;
    }
    
    public void setSourceversion(String sourceversion) {
        this.sourceversion = sourceversion;
    }
    
    @Column(name="sourceuri")
    public String getSourceuri() {
        return this.sourceuri;
    }
    
    public void setSourceuri(String sourceuri) {
        this.sourceuri = sourceuri;
    }
    
    @Column(name="reference_id")
    public Integer getReferenceId() {
        return this.referenceId;
    }
    
    public void setReferenceId(Integer referenceId) {
        this.referenceId = referenceId;
    }
    
    @Column(name="parameters")
    public Serializable getParameters() {
        return this.parameters;
    }
    
    public void setParameters(Serializable parameters) {
        this.parameters = parameters;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="timeexecuted", length=29)
    public Date getTimeexecuted() {
        return this.timeexecuted;
    }
    
    public void setTimeexecuted(Date timeexecuted) {
        this.timeexecuted = timeexecuted;
    }
    
    @Column(name="status", nullable=false)
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }




}


