package org.gobiiproject.gobiidao.entity.pojos;
// Generated Mar 31, 2016 1:44:38 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DatasetDnarun generated by hbm2java
 */
@Entity
@Table(name="dataset_dnarun"
    ,schema="public"
)
public class DatasetDnarun  implements java.io.Serializable {


     private int datasetDnarunId;
     private int datasetId;
     private int dnarunId;

    public DatasetDnarun() {
    }

    public DatasetDnarun(int datasetDnarunId, int datasetId, int dnarunId) {
       this.datasetDnarunId = datasetDnarunId;
       this.datasetId = datasetId;
       this.dnarunId = dnarunId;
    }
   
     @Id 
    
    @Column(name="dataset_dnarun_id", unique=true, nullable=false)
    public int getDatasetDnarunId() {
        return this.datasetDnarunId;
    }
    
    public void setDatasetDnarunId(int datasetDnarunId) {
        this.datasetDnarunId = datasetDnarunId;
    }
    
    @Column(name="dataset_id", nullable=false)
    public int getDatasetId() {
        return this.datasetId;
    }
    
    public void setDatasetId(int datasetId) {
        this.datasetId = datasetId;
    }
    
    @Column(name="dnarun_id", nullable=false)
    public int getDnarunId() {
        return this.dnarunId;
    }
    
    public void setDnarunId(int dnarunId) {
        this.dnarunId = dnarunId;
    }




}


