package org.gobiiproject.gobiidao.entity.pojos;
// Generated Mar 31, 2016 1:44:38 PM by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Dnasample generated by hbm2java
 */
@Entity
@Table(name="dnasample"
    ,schema="public"
)
public class Dnasample  implements java.io.Serializable {


     private int dnasampleId;
     private String dnasampleName;
     private String dnasampleCode;
     private String platename;
     private String dnasampleNum;
     private String wellRow;
     private String wellCol;
     private int projectId;
     private int germplasmId;
     private int createdBy;
     private Date createdDate;
     private int modifiedBy;
     private Date modifiedDate;
     private int status;

    public Dnasample() {
    }

	
    public Dnasample(int dnasampleId, String dnasampleName, String dnasampleCode, int projectId, int germplasmId, int createdBy, Date createdDate, int modifiedBy, Date modifiedDate, int status) {
        this.dnasampleId = dnasampleId;
        this.dnasampleName = dnasampleName;
        this.dnasampleCode = dnasampleCode;
        this.projectId = projectId;
        this.germplasmId = germplasmId;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.modifiedBy = modifiedBy;
        this.modifiedDate = modifiedDate;
        this.status = status;
    }
    public Dnasample(int dnasampleId, String dnasampleName, String dnasampleCode, String platename, String dnasampleNum, String wellRow, String wellCol, int projectId, int germplasmId, int createdBy, Date createdDate, int modifiedBy, Date modifiedDate, int status) {
       this.dnasampleId = dnasampleId;
       this.dnasampleName = dnasampleName;
       this.dnasampleCode = dnasampleCode;
       this.platename = platename;
       this.dnasampleNum = dnasampleNum;
       this.wellRow = wellRow;
       this.wellCol = wellCol;
       this.projectId = projectId;
       this.germplasmId = germplasmId;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.modifiedBy = modifiedBy;
       this.modifiedDate = modifiedDate;
       this.status = status;
    }
   
     @Id 
    
    @Column(name="dnasample_id", unique=true, nullable=false)
    public int getDnasampleId() {
        return this.dnasampleId;
    }
    
    public void setDnasampleId(int dnasampleId) {
        this.dnasampleId = dnasampleId;
    }
    
    @Column(name="dnasample_name", nullable=false)
    public String getDnasampleName() {
        return this.dnasampleName;
    }
    
    public void setDnasampleName(String dnasampleName) {
        this.dnasampleName = dnasampleName;
    }
    
    @Column(name="dnasample_code", nullable=false)
    public String getDnasampleCode() {
        return this.dnasampleCode;
    }
    
    public void setDnasampleCode(String dnasampleCode) {
        this.dnasampleCode = dnasampleCode;
    }
    
    @Column(name="platename")
    public String getPlatename() {
        return this.platename;
    }
    
    public void setPlatename(String platename) {
        this.platename = platename;
    }
    
    @Column(name="dnasample_num")
    public String getDnasampleNum() {
        return this.dnasampleNum;
    }
    
    public void setDnasampleNum(String dnasampleNum) {
        this.dnasampleNum = dnasampleNum;
    }
    
    @Column(name="well_row")
    public String getWellRow() {
        return this.wellRow;
    }
    
    public void setWellRow(String wellRow) {
        this.wellRow = wellRow;
    }
    
    @Column(name="well_col")
    public String getWellCol() {
        return this.wellCol;
    }
    
    public void setWellCol(String wellCol) {
        this.wellCol = wellCol;
    }
    
    @Column(name="project_id", nullable=false)
    public int getProjectId() {
        return this.projectId;
    }
    
    public void setProjectId(int projectId) {
        this.projectId = projectId;
    }
    
    @Column(name="germplasm_id", nullable=false)
    public int getGermplasmId() {
        return this.germplasmId;
    }
    
    public void setGermplasmId(int germplasmId) {
        this.germplasmId = germplasmId;
    }
    
    @Column(name="created_by", nullable=false)
    public int getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="created_date", nullable=false, length=13)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="modified_by", nullable=false)
    public int getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(int modifiedBy) {
        this.modifiedBy = modifiedBy;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="modified_date", nullable=false, length=13)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
    
    @Column(name="status", nullable=false)
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }




}


