package org.gobiiproject.gobiidao.entity.pojos;
// Generated Mar 31, 2016 1:44:38 PM by Hibernate Tools 3.2.2.GA


import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DnasampleProp generated by hbm2java
 */
@Entity
@Table(name="dnasample_prop"
    ,schema="public"
)
public class DnasampleProp  implements java.io.Serializable {


     private int dnasamplePropId;
     private int dnasampleId;
     private Serializable props;

    public DnasampleProp() {
    }

	
    public DnasampleProp(int dnasamplePropId, int dnasampleId) {
        this.dnasamplePropId = dnasamplePropId;
        this.dnasampleId = dnasampleId;
    }
    public DnasampleProp(int dnasamplePropId, int dnasampleId, Serializable props) {
       this.dnasamplePropId = dnasamplePropId;
       this.dnasampleId = dnasampleId;
       this.props = props;
    }
   
     @Id 
    
    @Column(name="dnasample_prop_id", unique=true, nullable=false)
    public int getDnasamplePropId() {
        return this.dnasamplePropId;
    }
    
    public void setDnasamplePropId(int dnasamplePropId) {
        this.dnasamplePropId = dnasamplePropId;
    }
    
    @Column(name="dnasample_id", nullable=false)
    public int getDnasampleId() {
        return this.dnasampleId;
    }
    
    public void setDnasampleId(int dnasampleId) {
        this.dnasampleId = dnasampleId;
    }
    
    @Column(name="props")
    public Serializable getProps() {
        return this.props;
    }
    
    public void setProps(Serializable props) {
        this.props = props;
    }




}


