package org.gobiiproject.gobiidao.entity.pojos;
// Generated Mar 31, 2016 1:44:38 PM by Hibernate Tools 3.2.2.GA


import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * GermplasmProp generated by hbm2java
 */
@Entity
@Table(name="germplasm_prop"
    ,schema="public"
)
public class GermplasmProp  implements java.io.Serializable {


     private int germplasmPropId;
     private int germplasmId;
     private Serializable props;

    public GermplasmProp() {
    }

	
    public GermplasmProp(int germplasmPropId, int germplasmId) {
        this.germplasmPropId = germplasmPropId;
        this.germplasmId = germplasmId;
    }
    public GermplasmProp(int germplasmPropId, int germplasmId, Serializable props) {
       this.germplasmPropId = germplasmPropId;
       this.germplasmId = germplasmId;
       this.props = props;
    }
   
     @Id 
    
    @Column(name="germplasm_prop_id", unique=true, nullable=false)
    public int getGermplasmPropId() {
        return this.germplasmPropId;
    }
    
    public void setGermplasmPropId(int germplasmPropId) {
        this.germplasmPropId = germplasmPropId;
    }
    
    @Column(name="germplasm_id", nullable=false)
    public int getGermplasmId() {
        return this.germplasmId;
    }
    
    public void setGermplasmId(int germplasmId) {
        this.germplasmId = germplasmId;
    }
    
    @Column(name="props")
    public Serializable getProps() {
        return this.props;
    }
    
    public void setProps(Serializable props) {
        this.props = props;
    }




}


