package org.gobiiproject.gobiidao.entity.pojos;
// Generated Mar 31, 2016 1:44:38 PM by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Manifest generated by hbm2java
 */
@Entity
@Table(name="manifest"
    ,schema="public"
)
public class Manifest  implements java.io.Serializable {


     private int manifestId;
     private String manifestName;
     private String manifestCode;
     private int createdBy;
     private Date createdDate;
     private int modifiedBy;
     private Date modifiedDate;

    public Manifest() {
    }

    public Manifest(int manifestId, String manifestName, String manifestCode, int createdBy, Date createdDate, int modifiedBy, Date modifiedDate) {
       this.manifestId = manifestId;
       this.manifestName = manifestName;
       this.manifestCode = manifestCode;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.modifiedBy = modifiedBy;
       this.modifiedDate = modifiedDate;
    }
   
     @Id 
    
    @Column(name="manifest_id", unique=true, nullable=false)
    public int getManifestId() {
        return this.manifestId;
    }
    
    public void setManifestId(int manifestId) {
        this.manifestId = manifestId;
    }
    
    @Column(name="manifest_name", nullable=false)
    public String getManifestName() {
        return this.manifestName;
    }
    
    public void setManifestName(String manifestName) {
        this.manifestName = manifestName;
    }
    
    @Column(name="manifest_code", nullable=false)
    public String getManifestCode() {
        return this.manifestCode;
    }
    
    public void setManifestCode(String manifestCode) {
        this.manifestCode = manifestCode;
    }
    
    @Column(name="created_by", nullable=false)
    public int getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="created_date", nullable=false, length=13)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="modified_by", nullable=false)
    public int getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(int modifiedBy) {
        this.modifiedBy = modifiedBy;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="modified_date", nullable=false, length=13)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }




}


