package org.gobiiproject.gobiidao.entity.pojos;
// Generated Mar 31, 2016 1:44:38 PM by Hibernate Tools 3.2.2.GA


import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MarkerGroup generated by hbm2java
 */
@Entity
@Table(name="marker_group"
    ,schema="public"
)
public class MarkerGroup  implements java.io.Serializable {


     private int markerGroupId;
     private String name;
     private String code;
     private Serializable markers;
     private String germplasmGroup;
     private String createdBy;
     private Date createDate;
     private String modifiedBy;
     private Date modifiedDate;
     private int status;

    public MarkerGroup() {
    }

	
    public MarkerGroup(int markerGroupId, String name, Serializable markers, int status) {
        this.markerGroupId = markerGroupId;
        this.name = name;
        this.markers = markers;
        this.status = status;
    }
    public MarkerGroup(int markerGroupId, String name, String code, Serializable markers, String germplasmGroup, String createdBy, Date createDate, String modifiedBy, Date modifiedDate, int status) {
       this.markerGroupId = markerGroupId;
       this.name = name;
       this.code = code;
       this.markers = markers;
       this.germplasmGroup = germplasmGroup;
       this.createdBy = createdBy;
       this.createDate = createDate;
       this.modifiedBy = modifiedBy;
       this.modifiedDate = modifiedDate;
       this.status = status;
    }
   
     @Id 
    
    @Column(name="marker_group_id", unique=true, nullable=false)
    public int getMarkerGroupId() {
        return this.markerGroupId;
    }
    
    public void setMarkerGroupId(int markerGroupId) {
        this.markerGroupId = markerGroupId;
    }
    
    @Column(name="name", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="code")
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    
    @Column(name="markers", nullable=false)
    public Serializable getMarkers() {
        return this.markers;
    }
    
    public void setMarkers(Serializable markers) {
        this.markers = markers;
    }
    
    @Column(name="germplasm_group")
    public String getGermplasmGroup() {
        return this.germplasmGroup;
    }
    
    public void setGermplasmGroup(String germplasmGroup) {
        this.germplasmGroup = germplasmGroup;
    }
    
    @Column(name="created_by")
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="create_date", length=13)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    
    @Column(name="modified_by")
    public String getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="modified_date", length=13)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
    
    @Column(name="status", nullable=false)
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }




}


