package org.gobiiproject.gobiidao.entity.pojos;
// Generated Mar 31, 2016 1:44:38 PM by Hibernate Tools 3.2.2.GA


import org.gobiiproject.gobiidao.usertypes.JSONBDocument;
import org.gobiiproject.gobiidao.usertypes.JSONBUserType;
import org.hibernate.annotations.Parameter;
import org.hibernate.annotations.Type;
import org.hibernate.annotations.TypeDef;

import java.io.Serializable;
import java.util.List;
import javax.persistence.*;

/**
 * Marker generated by hbm2java
 */
@TypeDef(name = "jsonb", typeClass = JSONBUserType.class, parameters = {
        @Parameter(name = JSONBUserType.CLASS,
                value = "org.gobiiproject.gobiidao.entity.pojos.Marker")})
@Entity
@Table(name = "marker"
        , schema = "public"
)
public class Marker {


    private int markerId;
    private int platformId;
    private Integer variantId;
    private String name;
    private String code;
    private String ref;

    @Transient
    private Serializable alts;

    private String sequence;
    private Integer referenceId;

    @Type(type = "jsonb")
    private List<JSONBDocument> primers;

    @Transient
    private Serializable probsets;

    private String strand;
    private int status;

    public Marker() {
    }


//    public Marker(int markerId, int platformId, String name, String code, String ref, Serializable alts, int status) {
//        this.markerId = markerId;
//        this.platformId = platformId;
//        this.name = name;
//        this.code = code;
//        this.ref = ref;
//        this.alts = alts;
//        this.status = status;
//    }
//
//    public Marker(int markerId, int platformId, Integer variantId, String name, String code, String ref, Serializable alts, String sequence, Integer referenceId, Serializable primers, Serializable probsets, String strand, int status) {
//        this.markerId = markerId;
//        this.platformId = platformId;
//        this.variantId = variantId;
//        this.name = name;
//        this.code = code;
//        this.ref = ref;
//        this.alts = alts;
//        this.sequence = sequence;
//        this.referenceId = referenceId;
//        this.primers = primers;
//        this.probsets = probsets;
//        this.strand = strand;
//        this.status = status;
//    }

    @Id

    @Column(name = "marker_id", unique = true, nullable = false)
    public int getMarkerId() {
        return this.markerId;
    }

    public void setMarkerId(int markerId) {
        this.markerId = markerId;
    }

    @Column(name = "platform_id", nullable = false)
    public int getPlatformId() {
        return this.platformId;
    }

    public void setPlatformId(int platformId) {
        this.platformId = platformId;
    }

    @Column(name = "variant_id")
    public Integer getVariantId() {
        return this.variantId;
    }

    public void setVariantId(Integer variantId) {
        this.variantId = variantId;
    }

    @Column(name = "name", nullable = false)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "code", nullable = false)
    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    @Column(name = "ref", nullable = false)
    public String getRef() {
        return this.ref;
    }

    public void setRef(String ref) {
        this.ref = ref;
    }

    @Column(name = "alts", nullable = false)
    public Serializable getAlts() {
        return this.alts;
    }

    public void setAlts(Serializable alts) {
        this.alts = alts;
    }

    @Column(name = "sequence")
    public String getSequence() {
        return this.sequence;
    }

    public void setSequence(String sequence) {
        this.sequence = sequence;
    }

    @Column(name = "reference_id")
    public Integer getReferenceId() {
        return this.referenceId;
    }

    public void setReferenceId(Integer referenceId) {
        this.referenceId = referenceId;
    }

    @Column(name = "primers")
    public List<JSONBDocument> getPrimers() {
        return this.primers;
    }

    public void setPrimers(List<JSONBDocument> primers) {
        this.primers = primers;
    }

    @Column(name = "probsets")
    public Serializable getProbsets() {
        return this.probsets;
    }

    public void setProbsets(Serializable probsets) {
        this.probsets = probsets;
    }

    @Column(name = "strand")
    public String getStrand() {
        return this.strand;
    }

    public void setStrand(String strand) {
        this.strand = strand;
    }

    @Column(name = "status", nullable = false)
    public int getStatus() {
        return this.status;
    }

    public void setStatus(int status) {
        this.status = status;
    }


}


