package org.gobiiproject.gobiidao.entity.pojos;
// Generated Mar 31, 2016 1:44:38 PM by Hibernate Tools 3.2.2.GA


import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MarkerProp generated by hbm2java
 */
@Entity
@Table(name="marker_prop"
    ,schema="public"
)
public class MarkerProp  implements java.io.Serializable {


     private int markerPropId;
     private int markerId;
     private Serializable props;

    public MarkerProp() {
    }

	
    public MarkerProp(int markerPropId, int markerId) {
        this.markerPropId = markerPropId;
        this.markerId = markerId;
    }
    public MarkerProp(int markerPropId, int markerId, Serializable props) {
       this.markerPropId = markerPropId;
       this.markerId = markerId;
       this.props = props;
    }
   
     @Id 
    
    @Column(name="marker_prop_id", unique=true, nullable=false)
    public int getMarkerPropId() {
        return this.markerPropId;
    }
    
    public void setMarkerPropId(int markerPropId) {
        this.markerPropId = markerPropId;
    }
    
    @Column(name="marker_id", nullable=false)
    public int getMarkerId() {
        return this.markerId;
    }
    
    public void setMarkerId(int markerId) {
        this.markerId = markerId;
    }
    
    @Column(name="props")
    public Serializable getProps() {
        return this.props;
    }
    
    public void setProps(Serializable props) {
        this.props = props;
    }




}


