package org.gobiiproject.gobiidao.entity.pojos;
// Generated Mar 31, 2016 1:44:38 PM by Hibernate Tools 3.2.2.GA


import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PlatformProp generated by hbm2java
 */
@Entity
@Table(name="platform_prop"
    ,schema="public"
)
public class PlatformProp  implements java.io.Serializable {


     private int platformPropId;
     private int platformId;
     private Serializable props;

    public PlatformProp() {
    }

	
    public PlatformProp(int platformPropId, int platformId) {
        this.platformPropId = platformPropId;
        this.platformId = platformId;
    }
    public PlatformProp(int platformPropId, int platformId, Serializable props) {
       this.platformPropId = platformPropId;
       this.platformId = platformId;
       this.props = props;
    }
   
     @Id 
    
    @Column(name="platform_prop_id", unique=true, nullable=false)
    public int getPlatformPropId() {
        return this.platformPropId;
    }
    
    public void setPlatformPropId(int platformPropId) {
        this.platformPropId = platformPropId;
    }
    
    @Column(name="platform_id", nullable=false)
    public int getPlatformId() {
        return this.platformId;
    }
    
    public void setPlatformId(int platformId) {
        this.platformId = platformId;
    }
    
    @Column(name="props")
    public Serializable getProps() {
        return this.props;
    }
    
    public void setProps(Serializable props) {
        this.props = props;
    }




}


