package org.gobiiproject.gobiidao.entity.pojos;
// Generated Mar 31, 2016 1:44:38 PM by Hibernate Tools 3.2.2.GA


import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ProjectProp generated by hbm2java
 */
@Entity
@Table(name="project_prop"
    ,schema="public"
)
public class ProjectProp  implements java.io.Serializable {


     private int projectPropId;
     private int projectId;
     private Serializable props;

    public ProjectProp() {
    }

	
    public ProjectProp(int projectPropId, int projectId) {
        this.projectPropId = projectPropId;
        this.projectId = projectId;
    }
    public ProjectProp(int projectPropId, int projectId, Serializable props) {
       this.projectPropId = projectPropId;
       this.projectId = projectId;
       this.props = props;
    }
   
     @Id 
    
    @Column(name="project_prop_id", unique=true, nullable=false)
    public int getProjectPropId() {
        return this.projectPropId;
    }
    
    public void setProjectPropId(int projectPropId) {
        this.projectPropId = projectPropId;
    }
    
    @Column(name="project_id", nullable=false)
    public int getProjectId() {
        return this.projectId;
    }
    
    public void setProjectId(int projectId) {
        this.projectId = projectId;
    }
    
    @Column(name="props")
    public Serializable getProps() {
        return this.props;
    }
    
    public void setProps(Serializable props) {
        this.props = props;
    }




}


