package org.gobiiproject.gobiiapimodel.types;

/**
 * Created by Phil on 5/13/2016.
 */
public enum ServiceRequestId {
    UNKNOWN,
    URL_AUTH,
    URL_PING_EXTRACT,
    URL_PING,
    URL_PROJECTS,
    URL_NAME_ID_LIST_DEPRECATED,
    URL_NAMES,
    URL_FILE_LOAD,
    URL_FILE_LOAD_INSTRUCTIONS,
    URL_FILE_EXTRACTOR_INSTRUCTIONS,
    URL_FILE_EXTRACTOR_STATUS,
    URL_DISPLAY,
    URL_CV,
    URL_CONTACTS,
    URL_CONTACT_SEARCH,
    URL_ORGANIZATION_SEARCH,
    URL_REFERENCE,
    URL_EXPERIMENTS,
    URL_DATASETS,
    URL_ANALYSIS,
    URL_MARKERGROUP,
    URL_MANIFEST,
    URL_ORGANIZATION,
    URL_PLATFORM,
    URL_MAPSET,
    URL_CONFIGSETTINGS,
    URL_ROLES,
    URL_MARKERS,
    URL_MARKER_SEARCH,
    URL_CALLS,
    URL_STUDIES_SEARCH,
    URL_STUDIES,
    URL_GERMPLASM,
    URL_OBSERVATION_VARIABLES,
    URL_PROTOCOL,
    URL_VENDORS
}
